main: order.h order.cpp orderTest.cpp
	clear
	g++ -o test orderTest.cpp order.h order.cpp
	./test
	rm test

debug: order.h order.cpp orderTest.cpp
	clear
	g++ -g orderTest.cpp order.h order.cpp
	gdb a.out

